webapp/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, send_file # Importarea funcțiilor și claselor necesare din Flask
from flask_login import  login_required, current_user # Importarea funcțiilor și claselor necesare pentru autentificare
from .models import Note, User, db # Importarea claselor și a instanței bazei de date
from datetime import date, datetime # Importarea claselor pentru lucrul cu datele și timpul
from apscheduler.schedulers.background import BackgroundScheduler # Importarea clasei pentru programarea sarcinilor periodice
from collections import defaultdict # Importarea clasei pentru crearea unui dicționar cu valori implicite
from sqlalchemy import extract # Importarea funcției pentru extragerea datelor din baza de date
import pandas as pd # Importarea bibliotecii pentru lucrul cu datele în format tabular
import openpyxl # Importarea bibliotecii pentru lucrul cu fișierele Excel
from io import BytesIO # Importarea clasei pentru lucrul cu fluxurile de octeți
import calendar # Importarea clasei pentru lucrul cu calendarul
import sqlalchemy # Importarea clasei pentru lucrul cu baza de date
import csv # Importarea clasei pentru lucrul cu fișierele CSV
import tempfile # Importarea clasei pentru lucrul cu fișierele temporare

# Inițializarea unui Blueprint Flask pentru aceste rute
views = Blueprint('views', __name__)

# Dicționarul pentru a stoca totalul de ore pentru fiecare utilizator în fiecare lună
monthly_totals = {}

# Crearea unui scheduler pentru a programa acțiuni periodice
scheduler = BackgroundScheduler()


def check_database(): # Funcția care verifică baza de date și returnează înregistrările pentru fiecare lună
    # Inițializează un dicționar pentru a stoca numele lunilor cu înregistrări ale utilizatorului curent
    months_with_records = defaultdict(list) # Un dicționar pentru a stoca înregistrările pentru fiecare lună
    months_with_totals = {} # Un dicționar pentru a stoca totalul de ore pentru fiecare lună

    # Obține toate înregistrările din baza de date pentru utilizatorul curent
    all_notes = Note.query.filter_by(user_id=current_user.id).all()

    # Parcurge fiecare înregistrare și adaugă înregistrările corespunzătoare lunii în dicționar
    for note in all_notes: # Parcurgem fiecare înregistrare a utilizatorului curent
        note_date = datetime.strptime(note.date, '%Y-%m-%d') # Obținem data înregistrării
        month_name = note_date.strftime("%B") # Obținem numele lunii
        months_with_records[month_name].append({ # Adăugăm înregistrarea în dicționarul corespunzător lunii
            'date': note.date, # Data înregistrării
            'hours': note.hours, # Numărul de ore
            'project': note.project, # Proiectul
            'description': note.description # Descrierea
        }) # Adăugăm înregistrarea în dicționarul corespunzător lunii

    # Calculează totalul orelor pe fiecare lună și adaugă totalul în dicționarul separat
    for month, records in months_with_records.items(): # Parcurgem fiecare lună și înregistrările corespunzătoare
        total_hours = sum(record['hours'] for record in records) # Calculăm totalul de ore pentru fiecare lună
        months_with_totals[month] = { # Adăugăm totalul de ore pentru fiecare lună în dicționarul separat
            'records': records, # Înregistrările pentru lună
            'total_hours': total_hours # Totalul de ore pentru lună
        } # Adăugăm totalul de ore pentru fiecare lună în dicționarul separat

    return months_with_totals # Returnăm dicționarul cu totalul de ore pentru fiecare lună


def scheduled_task(): # Funcția pentru programarea sarcinilor periodice
    # Calcularea totalului de ore pentru fiecare utilizator și stocarea acestuia în dicționar
    details = [] # O listă pentru a stoca detaliile pentru toți utilizatorii
    users_same_company = User.query.filter_by(company=current_user.company).all() # Obținem toți utilizatorii din aceeași companie
    for user in users_same_company: # Parcurgem fiecare utilizator și calculam totalul de ore pentru fiecare utilizator
        user_total = totals(user.id) # Obținem totalul de ore pentru utilizatorul curent
        user_details = [] # O listă pentru a stoca detaliile pentru utilizatorul curent
        current_date = datetime.now() # Obținem data curentă
        first_day_of_month = datetime(current_date.year, current_date.month, 1) # Obținem prima zi a lunii curente

        for note in user.dates: # Parcurgem fiecare înregistrare a utilizatorului și adăugăm detaliile pentru utilizatorul curent
            note_date = datetime.strptime(note.date, '%Y-%m-%d') # Obținem data înregistrării
            if note_date >= first_day_of_month and note_date <= current_date: # Verificăm dacă înregistrarea este în luna curentă
                user_details.append({ # Adăugăm detaliile în lista de detalii pentru utilizatorul curent
                    'date': note.date, # Data înregistrării
                    'hours': note.hours,  # Numărul de ore
                    'project': note.project, # Proiectul
                    'description': note.description # Descrierea
                })
        details.extend(user_details) # Adăugăm detaliile pentru utilizatorul curent la lista globală de detalii
        monthly_totals[user.id] = { # Adăugăm totalul de ore pentru utilizatorul curent în dicționarul global
            'total': user_total, # Totalul de ore pentru utilizator
            'month': datetime.now().strftime("%B"), # Numele lunii curente
            'details': user_details # Detaliile pentru utilizatorul curent
        }
    monthly_totals['details'] = details # Adăugăm detalii pentru toți utilizatorii în dicționarul global
scheduler.add_job(scheduled_task, 'cron', hour=0) # Adăugarea sarcinii periodice la scheduler
scheduler.start() # Pornirea schedulerului


@views.route("/download_data", methods=["GET"]) # Ruta pentru descărcarea datelor
@login_required # Asigurarea că utilizatorul este autentificat
def download_data(): # Funcția pentru descărcarea datelor
    """
    Funcția pentru descărcarea datelor în format Excel pentru luna curentă, sortate pe lună și an, cu denumirea lunii în antet.
    """
    current_month = datetime.now().month # Obține luna curentă
    current_year = datetime.now().year # Obține anul curent
    all_users = User.query.filter_by(company=current_user.company).all() # Obține toți utilizatorii din aceeași companie
    wb = openpyxl.Workbook() # Creează un workbook Excel
    ws = wb.active # Creează o foaie de lucru
    month_name = calendar.month_name[current_month] # Obține numele lunii curente
    ws.append(['Nume', 'Prenume', 'Data', 'Ore', 'Proiect', 'Descriere', 'Luna']) # Adaugă antetele în fișierul Excel
    sorted_notes = [] # O listă pentru a stoca toate notele sortate
    # Adaugă datele pentru fiecare utilizator pentru luna curentă
    for user in all_users: # Parcurgem fiecare utilizator
        for note in user.dates: # Parcurgem fiecare înregistrare a utilizatorului
            note_date = datetime.strptime(note.date, '%Y-%m-%d') # Obținem data înregistrării
            if note_date.month == current_month and note_date.year == current_year: # Verificăm dacă înregistrarea este în luna curentă
                sorted_notes.append((note_date, user.last_name, user.first_name, note.date, note.hours, note.project, note.description)) # Adăugăm înregistrarea în lista de note sortate
    sorted_notes.sort(key=lambda x: x[1]) # Sortează notele după numele de familie al utilizatorului
    # Adaugă datele sortate în fișierul Excel
    for note_data in sorted_notes: # Parcurgem fiecare înregistrare sortată
        ws.append([note_data[1], note_data[2], note_data[3], note_data[4], note_data[5], note_data[6], month_name]) # Adaugăm înregistrarea în fișierul Excel
    # Salvează workbook-ul într-un flux BytesIO
    excel_file = BytesIO() # Creează un flux BytesIO
    file_name = f'database_{current_user.company.lower()}_{calendar.month_name[current_month]}.xlsx'  # Creează un nume de fișier
    wb.save(excel_file) # Salvează workbook-ul în fluxul BytesIO
    excel_file.seek(0) # Setează cursorul la începutul fișierului
    return send_file(excel_file, as_attachment=True, download_name=file_name) # Returnează fișierul pentru descărcare

@views.route("/download_data_csv", methods=["GET"]) # Ruta pentru descărcarea datelor în format CSV
@login_required # Asigurarea că utilizatorul este autentificat
def download_data_csv(): # Funcția pentru descărcarea datelor în format CSV
    """
    Funcția pentru descărcarea datelor în format CSV pentru luna curentă, sortate pe lună și an, cu denumirea lunii în antet.
    """
    current_month = datetime.now().month # Obține luna curentă
    current_year = datetime.now().year # Obține anul curent
    all_users = User.query.filter_by(company=current_user.company).all() # Obține toți utilizatorii din aceeași companie
    with tempfile.NamedTemporaryFile(mode='w', delete=False) as tmp_file: # Creează un fișier temporar CSV
        csv_writer = csv.writer(tmp_file) # Creează un obiect CSV writer
        csv_writer.writerow(['Nume', 'Prenume', 'Data', 'Ore', 'Proiect', 'Descriere', 'Luna']) # Adaugă antetele în fișierul CSV
        # Adaugă datele pentru fiecare utilizator pentru luna curentă
        for user in all_users: # Parcurgem fiecare utilizator
            for note in user.dates: # Parcurgem fiecare înregistrare a utilizatorului
                note_date = datetime.strptime(note.date, '%Y-%m-%d') # Obținem data înregistrării
                if note_date.month == current_month and note_date.year == current_year: # Verificăm dacă înregistrarea este în luna curentă
                    csv_writer.writerow([user.last_name, user.first_name, note.date, note.hours, note.project, note.description, calendar.month_name[current_month]]) # Adaugăm înregistrarea în fișierul CSV

webapp/templates/about.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock %}
{% block content %}
<br>
<div class="container">
  <div class="row justify-content-center align-items-baseline">
    <div class="col text-center">
        <span class="fa fa-question-circle fa-2x text-dark"></span>
      <h3 class="d-inline-block mb-0 text-success fa-1x "> </h3>
      <h3 class="d-inline-block mb-0 fa-1x" >About</h3>
    </div>
  </div>
</div>
<span class="bottom-right  cursor-pointer fa fa-language" onclick="translateText()" alt="Translate"></span>


<section class="py-5">
	<div class="container">
		<div class="row align-items-center gx-4">
			<div class="col-md-5">
				<div class="ms-md-2 ms-lg-5"><img class="img-fluid rounded-3" src="../static/img/work.png"></div>
				<br>
				<div class="ms-md-2 ms-lg-5"><img class="img-fluid rounded-3" src="../static/img/about.png"></div>
			</div>
			<div class="col-md-6 offset-md-1">
				<div class="ms-md-2 ms-lg-5">
					<span id="p0" class="text-muted">Our Story</span>
					<h2 id="pt" class="display-5 fw-bold">About Us</h2>
					<p id="p1" class="lead">With love and passion for efficiency, we have created a web application that defines a new paradigm in managing hourly workers. Welcome to the heart and brain of our digital world, where we set out to transform the way companies manage their workforce.</p>
					<p id="p2" class="lead mb-0">With every line of code, we have dedicated ourselves to bringing a solution that reconciles the complex needs of employees with the rigorous requirements of administrators. Behind the intuitive interface and modern design lies a platform that guides each user towards efficiency and performance.</p>
						<br>
					<p  id="p3" class="lead mb-0">For our workers, it is a versatile tool that offers them the freedom to manage their working hours with ease and precision. Whether they are in the field or in the office, they can record every detail related to their projects, ensuring impeccable work records.</p>
						<br>
					<p id="p4" class="lead mb-0">More than just an application, we are a passionate team that believes in the power of technology to transform the way we work. With every update and every feedback received, we aim to continue evolving and bringing innovation to the professional environment.</p>
						<br>
					<p id="p5" class="lead mb-0">Join us on the journey towards efficiency and performance, and together we will create a future where work is simplified and valued equally. Welcome to a new era of workforce management!</p>
				</div>
			</div>
		</div>
	</div>
</section>
<script>

let translated = false;

function translateText() {
  if (!translated) {
	document.getElementById("p0").innerHTML = "Our Story";
	document.getElementById("pt").innerHTML = "About Us";
    document.getElementById("p1").innerHTML = "With love and passion for efficiency, we have created a web application that defines a new paradigm in managing hourly workers. Welcome to the heart and brain of our digital world, where we set out to transform the way companies manage their workforce.";
    document.getElementById("p2").innerHTML = "With every line of code, we have dedicated ourselves to bringing a solution that reconciles the complex needs of employees with the rigorous requirements of administrators. Behind the intuitive interface and modern design lies a platform that guides each user towards efficiency and performance.";
    document.getElementById("p3").innerHTML = "For our workers, it is a versatile tool that offers them the freedom to manage their working hours with ease and precision. Whether they are in the field or in the office, they can record every detail related to their projects, ensuring impeccable work records.";
    document.getElementById("p4").innerHTML = "More than just an application, we are a passionate team that believes in the power of technology to transform the way we work. With every update and every feedback received, we aim to continue evolving and bringing innovation to the professional environment.";
    document.getElementById("p5").innerHTML = "Join us on the journey towards efficiency and performance, and together we will create a future where work is simplified and valued equally. Welcome to a new era of workforce management!";
    translated = true;
  } else {
	document.getElementById("p0").innerHTML = "Povestea Noastră";
	document.getElementById("pt").innerHTML = "Despre Noi";
    document.getElementById("p1").innerHTML = "Cu dragoste și pasiune pentru eficiență, am creat o aplicație web ce definește o nouă paradigmă în gestionarea lucrătorilor plătiți la oră. Bine ați venit la inima și creierul nostru digital, unde ne-am propus să transformăm modul în care companiile își gestionează forța de muncă.";
    document.getElementById("p2").innerHTML = "Cu fiecare linie de cod, ne-am dedicat să aducem o soluție care să împace nevoile complexe ale angajaților și cerințele riguroase ale administratorilor. În spatele interfeței intuitive și a designului modern, se ascunde o platformă ce ghidează fiecare utilizator către eficiență și performanță.";
    document.getElementById("p3").innerHTML = "Pentru lucrătorii noștri, este un instrument versatil ce le oferă libertatea de a-și gestiona orele lucrate cu ușurință și precizie. Indiferent dacă sunt pe teren sau în birou, pot înregistra fiecare detaliu legat de proiectele lor, asigurând astfel o evidență impecabilă a muncii lor.";
    document.getElementById("p4").innerHTML = "Mai mult decât o simplă aplicație, suntem o echipă pasionată care crede în puterea tehnologiei de a transforma modul în care lucrăm. Cu fiecare actualizare și fiecare feedback primit, ne propunem să continuăm să evoluăm și să aducem inovație în mediul profesional.";
    document.getElementById("p5").innerHTML = "Alăturați-vă nouă în călătoria către eficiență și performanță, iar împreună vom crea un viitor în care munca este simplificată și valorizată în mod egal. Welcome to a new era of workforce management!";
    translated = false;
  }
}
</script>
<style>
  .bottom-right {
    position: fixed;
    bottom: 35px;
    right: 10px;
    padding: 10px;
    background-color: white;
    border: 1px solid black;
    border-radius: 5px;
  }
  .cursor-pointer {
    cursor: pointer;
  }
</style>
{% endblock %}

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="icon" type="image/x-icon" href="../static/img/favicon.ico">
     <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
</head>
    <style>
    @media screen and (min-width: 770px) {
    #copyright::after{
        content: " 2024";
    }
}
        </style>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
 </button>
    <div class="collapse navbar-collapse w-100 order-1 order-md-0 dual-collapse2" id="navbar">
    <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
        <a class="nav-link fa fa-home" id="home" href="/">  Home</a>
      </li>
         <li class="nav-item active">
        <a class="nav-link fa fa-bar-chart" href="/monthly_statement">  Summary</a>
        </li>
      <li class="nav-item active">
        <a class="nav-link fa fa-address-book" href="/contacts">  Contacts</a>
      </li>
        {% if user.id == 1 %}
        <li class="nav-item">
        <a class="nav-link fa fa-wrench" href="/admin">  Admin Panel</a>
        </li>
            {% endif %}
        {% if user.is_admin%}
        <li class="nav-item">
        <a class="nav-link fa fa-cogs" href="/control_panel">  Control Panel</a>
        </li>
        {% endif %}
        <li class="nav-item active">
        <a class="nav-link fa fa-sign-out" id="logout" href="/logout">Logout</a>
      </li>
        <li class="nav-item">
        <a class="nav-link fa fa-question-circle" href="/about">  About</a>
      </li>
  <li class="nav-item active">
        <a class="nav-link fa fa-comment" href="/feedback"></a>
      </li>
    </ul>
    </ul>
    </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <p class="text-light h6">Welcome &nbsp;</p>
            </li>
            <li class="nav-item">
            <p class="text-success h6">{{ user.username }}</p>
            </li>

        {% else %}
        <li class="nav-item active">
        <a class="nav-link  fa fa-sign-in" id="login" href="/login">  Login</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link fa fa-user-plus" id="signup" href="/sign-up">  Sign Up</a>
      </li>
            <li class="nav-item">
        <a class="nav-link fa fa-question-circle" href="/about">  About</a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
     <ul>
        {% for category, message in messages %}
         {% if category == 'error' %}
          <div class="alert alert-danger alert-dismissable fade show" role="alert">
            {{ message }}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            </div>
        {% else %}
         <div class="alert alert-success alert-dismissable fade show" role="alert">
            {{ message }}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            </div>
        {% endif %}
        {% endfor %}
      </ul>
  {% endif %}
{% endwith %}
<div class="container mt-auto">
    {% block content %}
    {% endblock %}
</div>
<script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
<div class="container-fluid">
    <br>
  <footer class="footer fixed-bottom bg-light border-top">
    <div class="container">
      <div class="row d-flex flex-wrap justify-content-between align-items-center">
        <div class="col-md-4 w-25 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <li class="px-2 ms-3 fa fa-circle fa-x text-success" title="Ready"><a class="text-muted" ></a></li>
          </a>
        </div>
        <div class="col-md-4 w-25 text-center">
          <span id="copyright" class="text-muted">©TideTime</span>
        </div>
        <div class="col-md-4 w-25 d-flex justify-content-end">
          <ul class="nav list-unstyled">
            <li class="ms-3"><a class="text-muted" href="https://github.com/dordea"><i title="Github Project" class="fa fa-github fa-2x"></i></a></li>
            <li class="ms-3"><a class="text-muted" href="#"></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</div>

</body>
</html>

webapp/templates/control_panel.html
{% extends 'base.html' %}
{% block title %}Control panel{% endblock %}
{% block content %}
<br>
<style>
        @media screen and (max-width: 770px) {
    .pull-left,
    .pull-right {
        width: 100% !important;
    }
}
</style>
<div class="container">
  <div class="row justify-content-center align-items-baseline">
    <div class="col text-center">
        <span class="fa fa-cogs fa-2x text-dark"></span>
      <h3 class="d-inline-block mb-0 text-success fa-1x "> </h3>
      <h3 class="d-inline-block mb-0 fa-1x">Control Panel</h3>
    </div>
  </div>
</div>
<br>

<div class="mt-3">
    <div class="d-flex align-items-center justify-content-center">
    <div class="form-group border border-dark rounded center w-75  px-5 py-1">

      <div class="row justify-content-center align-items-baseline">
    <div class="col text-center">
        <span class="fa fa-users fa-2x text-dark"></span>
      <h3 class="d-inline-block mb-0 text-success fa-1x "> </h3>
      <h3 class="d-inline-block mb-0 fa-1x my-3">Users</h3>
        <div class="pull-left">
    {% set download_url = url_for('views.download_data') %}
     <button class="btn btn-success fa fa-download w-100 my-3" id="downloadButtonexcel" onclick="window.location.href='{{ download_url }}'"> Excel</button>
 </div>

 <div class="pull-right">
      {% set download_url_db = url_for('views.download_data_csv') %}
     <button class="btn btn-success fa fa-download w-100 my-3" id="downloadButtondb" onclick="window.location.href='{{ download_url_db }}'"> CSV</button>

 </div>
    </div>
  </div>

    </div></div>
    <div class="d-flex align-items-center justify-content-center">

    <div class="form-group border border-dark rounded center w-100  px-5 py-1">
    <!-- urmatoarea secventa de cod arata datele din baza de date -->
<ul class="list-group list-group-flush">
  {% for user in users %}
    <li class="list-group-item  fa fa-calendar btn text-info" onclick="toggleRecords('{{ user.id }}')">
      <a>{{ user.first_name }} {{ user.last_name }} ({{ counted[user.id] }} record/s)</a>
    </li>
    <div id="records_{{ user.id }}" style="display: none;">
      <ul>
        {% for note in details[user.id] %}

        <li class="list-inline btn text-dark fa fa-edit" id="note_{{ note.id }}" onclick="show('{{note.date}}')"> {{ note.date }}</li>

        <div id="{{note.date}}" style="display: none;" class=" rounded borderborder-dark px-3 py-1">
             <ul class="list-inline d-flex justify-content-center">
                <li class="list-inline-item" id="notes_{{ note.id }}">
                <input id="{{note.id}}.{{ note.hours }}" class="list-inline-item mb-3 text-danger" size="1" value="{{ note.hours }}">hours on
                <input id="{{note.id}}.{{ note.project }}" class="list-inline-item text-danger" size="9" value=" {{ note.project }}"> -
                <input id="{{note.id}}.description" class="list-inline-item text-danger" size="20" value="{{ note.description }}"></li>
                <button id="s{{note.date}}" onclick="editRecord('{{ note.id }}','{{note.hours}}','{{note.project}}','{{note.date}}')" class="list-inline-item btn btn-warning fa fa-pencil h-25"></button>
             </ul>
        </div><br>
         <!--<li class ="btn text-info" onclick="" >{{ note.date }} - {{ note.hours }} ore - {{ note.project }} - {{ note.description }}</li>-->
        {% endfor %}
      </ul>
    </div>
  {% endfor %}
</ul>

</div>
</div>
</div>
<br>
<script>
     function editRecord(noteId, hour, projects, date) {
    // Obțineți valorile pe care doriți să le trimiteți către server
    var description = document.getElementById(noteId + ".description").value;
    var hours = document.getElementById(noteId + "." + hour).value;
    var project = document.getElementById(noteId + "." + projects).value;

  console.log(`noteId: ${noteId}`);
console.log(`hours: ${hour}`);
console.log(`project: ${projects}`);
console.log(`description: ${description}`);
console.log(`date: ${date}`);
         // Trimiteți datele către server
    fetch('/update_data', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          note_id: noteId,
          hours: hours,
          project: project,
          description: description,
          date: date
        })
      })
      .then(function(response) {
        if (!response.ok) {
            // throw new Error('A apărut o eroare la actualizarea datelor');
        }
        return response.json();
    })
    .then(function(data) {
        //alert('Datele au fost actualizate cu succes!');
        window.location.reload();
        // Aici puteți face alte acțiuni după ce datele au fost actualizate cu succes
    })
    .catch(function(error) {
        //alert(error.message);
        // Aici puteți trata erorile, dacă este necesar
    });
    return false;

  }

   function show(date) {

    // Afiseaza div-ul corespunzator datei
    var targetDiv = document.getElementById(date);
    if (targetDiv.style.display === 'none') {
      targetDiv.style.display = 'block';
    } else {
      targetDiv.style.display = 'none';
    }
  }
function toggleRecords(userId) {
  var recordsDiv = document.getElementById('records_' + userId);
  if (recordsDiv.style.display === 'none') {
    recordsDiv.style.display = 'block';
    // Aici puteți încărca și afișa înregistrările din baza de date pentru utilizatorul cu ID-ul 'userId'
  } else {
    recordsDiv.style.display = 'none';
  }
}
</script>

{% endblock %}

webapp/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<br>
<div class="container">
  <div class="row justify-content-center align-items-baseline">
    <div class="col text-center">
        <span class="fa fa-sign-in fa-2x text-dark"></span>
      <h3 class="d-inline-block mb-0 text-success fa-1x "> </h3>
      <h3 class="d-inline-block mb-0 fa-1x">Login</h3>
    </div>
  </div>
</div>
<br>

<form method="POST">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}